server:
  port: 5002
spring:
  application:
    name: TASK-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Arunpyk7@
    url: jdbc:mysql://localhost:3306/task_services


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


